/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 9c9635b15157726c2a1930b29ae662fe)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		KV_CACHE: KVNamespace;
		KV_SESSIONS: KVNamespace;
		STORAGE: R2Bucket;
		DB: D1Database;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
